branches:
  only:
  - master
services:
- docker
before_install:
- docker pull osones/revealjs-builder:stable
- docker pull osones/wkhtmltopdf:stable
script:
- "/bin/bash build.sh"
deploy:
- provider: s3
  skip_cleanup: true
  access_key_id: "$access_key_id"
  secret_access_key: "$secret_access_key"
  bucket: formations.osones.com
  region: eu-west-1
  acl: public_read
  local_dir: output-html
- provider: s3
  skip_cleanup: true
  access_key_id: "$access_key_id"
  secret_access_key: "$secret_access_key"
  bucket: formations.osones.com
  region: eu-west-1
  acl: public_read
  local_dir: output-pdf
  upload-dir: pdf
notifications:
  slack:
    secure: X9K/xK3B04pyZzxB7jpQceG0etSD1ieztL+ERq6ogtMPy9p2lX0vmt8IxTG0P8yJll4OAofznQpDJmtRUPUIfOTrMUU8MnhZP9p5PROGIlC4BQFN1OkPlh+8y4ZFmLqVp/r5O38DCLqbweKq8fK3/L0iO/jPTh4hSWgR4NXw5Q8=
