<<<<<<< HEAD
language: python
install:
  - sudo apt-get install texlive-lang-french texlive texlive-latex3
script:
  - make
  - test -s screen.pdf
  - test -s handout.pdf
  - test -s print.pdf
branches:
  only:
    - master
    - integration
=======
install:
    - sudo apt-get install texlive-lang-french texlive texlive-latex-recommended
 
script:
    - make
>>>>>>> 8de7e2d68d40228c44d3fbc17b7b4fb58f906898
