branches:
  only:
  - master
services:
  - docker
before_install:
  - docker pull osones/revealjs-builder:stable
  - docker pull osones/wkhtmltopdf:stable
script:
    - "/bin/bash -x build.sh -o all -t osones -u https://osones.com/revealjs"
deploy:
- provider: s3
  skip_cleanup: true
  access_key_id: "$access_key_id"
  secret_access_key: "$secret_access_key"
  bucket: formations.osones.com
  region: eu-west-1
  acl: public_read
  local_dir: output-html
- provider: s3
  skip_cleanup: true
  access_key_id: "$access_key_id"
  secret_access_key: "$secret_access_key"
  bucket: formations.osones.com
  region: eu-west-1
  acl: public_read
  local_dir: output-pdf
  upload-dir: pdf
- provider: s3
  skip_cleanup: true
  access_key_id: "$access_key_id"
  secret_access_key: "$secret_access_key"
  bucket: osones-training
  region: eu-west-1
  acl: public_read
  local_dir: output-html
  upload-dir: formations
- provider: s3
  skip_cleanup: true
  access_key_id: "$access_key_id"
  secret_access_key: "$secret_access_key"
  bucket: osones-training
  region: eu-west-1
  acl: public_read
  local_dir: output-pdf
  upload-dir: formations/pdf
notifications:
  slack:
    secure: fgpNzg6JIzg+QYwXuVgC6WsvZ9eiU57pl5y0WoDy8AEXUKIYDDdcBHCL7HQyveLvJQxWJs2FeLObk9invzQSJN2S5pXi83c99Z5aWFv2aZBazV3eAgFP4MlUUKVbsq4h/NytN7pfDNqA2aafky0YSCeKrlg9mA6fKN9TvsELmRI=
